package com.bol.mancala.service.impl;

import com.bol.mancala.service.GameService;
import com.bol.mancala.web.model.GameDto;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DisplayName("Test Game Service")
@SpringBootTest
class GameServiceImplTest {

  protected static final long FIRST_PLAYER_ID = 1L;
  protected static final long SECOND_PLAYER_ID = 2L;

  @Autowired
  private GameService gameService;

  @DisplayName("Create New Game")
  @Test
  void createNewGame() {
    GameDto gameDto = GameDto.builder()
        .firstPlayerId(FIRST_PLAYER_ID)
        .secondPlayerId(SECOND_PLAYER_ID)
        .build();
    GameDto newGame = gameService.createNewGame(gameDto);

    verifyAutoGeneratedFields(newGame);

    assertEquals(FIRST_PLAYER_ID, newGame.getFirstPlayerId());
    assertEquals(SECOND_PLAYER_ID, newGame.getSecondPlayerId());
  }

  private void verifyAutoGeneratedFields(GameDto newGame) {
    assertNotNull(newGame.getId());
    assertNotNull(newGame.getVersion());
    assertNotNull(newGame.getCreatedDate());
    assertNotNull(newGame.getLastModifiedDate());
    assertNotNull(newGame.getBoard());
  }

}
